---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "getrnas"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::biopython=1.82
  - bioconda::gffutils=0.12
  - bioconda::pyfaidx=0.8.0
